# -*- conf -*-

include=~/.cache/wal/colors-foot.ini
font=Iosevka Nerd Font:size=11
font-bold=Iosevka Nerd Font:style=Bold:size=11
font-italic=Iosevka Nerd Font:style=Italic:size=11
pad=12x12
dpi-aware=yes

[cursor]
style=beam
blink=no

[mouse]
hide-when-typing=yes

[scrollback]
lines=5000
multiplier=3.0

[url]
launch=xdg-open ${url}
osc8-underline=url-mode

[colors-dark]
alpha=0.95

[csd]
preferred=server
size=0

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
search-start=Control+Shift+r
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0
spawn-terminal=Control+Shift+n
