# --- Autostart & Daemons ---
exec avizo-service
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
exec wal -R
exec_always swaybg -i $(cat ~/.cache/wal/wal) -m fill
