# --- Autostart & Daemons ---
exec swayosd-server --style ~/.config/swayosd/style.css
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
exec ~/.config/sway/scripts/wal-theme.sh -R
exec_always swaybg -i $(cat ~/.cache/wal/wal) -m fill
