# --- Status Bar (Laptop) ---
bar {
    output eDP-1
    position top
    height 40
    status_command ~/.config/sway/scripts/status.sh
    font pango:JetBrainsMono Nerd Font 12

    colors {
        statusline $color7
        background $color0
        focused_workspace  $color1 $color1 $color0
        active_workspace   $color2 $color2 $color0
        inactive_workspace $color0 $color0 $color7
        urgent_workspace   $color4 $color4 $color0
    }
}

# --- Status Bar (External) ---
bar {
    output HDMI-A-2
    position top
    height 30
    status_command ~/.config/sway/scripts/status.sh
    font pango:JetBrainsMono Nerd Font 9

    colors {
        statusline $color7
        background $color0
        focused_workspace  $color1 $color1 $color0
        active_workspace   $color2 $color2 $color0
        inactive_workspace $color0 $color0 $color7
        urgent_workspace   $color4 $color4 $color0
    }
}
